#!/bin/bash

## Make sure PSPDEV is set
if [ -z "${PS3DEV}" ]; then
    echo "The PS3DEV environment variable has not been set"
    exit 1
fi

if [ ! -d "${PS3DEV}" ]; then
    echo "${PS3DEV} does not exist"
    exit 2
fi

## Export makepkg variables
export PACMAN=ps3-pacman
export MAKEPKG_CONF="${PS3DEV}/etc/makepkg.conf"

## Add the directory with pacman's binaries to the start of the PATH
export PATH="${PS3DEV}/share/pacman/bin:${PATH}"

## Run makepkg
CARCH="$(${PS3DEV}/share/pacman/bin/get-arch)"  makepkg "$@"
